<?php
/**
 * Fallback SEO helpers.
 *
 * @package kitstroy-moscow
 */

defined( 'ABSPATH' ) || exit;

/**
 * Title of the current view.
 *
 * @param string $fallback Title part generated by WordPress for the current view.
 *                         It is passed in by the callers instead of calling
 *                         wp_get_document_title() here: that function applies the
 *                         document_title_parts filter, so calling it from this
 *                         function would recurse endlessly.
 * @return string
 */
function kitstroy_get_meta_title( string $fallback = '' ): string {
	if ( is_front_page() ) {
		return kitstroy_get_theme_option( 'home_seo_title', 'КИТ-Строй.Москва | Электромонтаж и инженерные системы в Москве' );
	}

	if ( is_singular( array( 'service', 'portfolio' ) ) ) {
		return kitstroy_get_post_field_value( 'seo_title', get_the_ID(), $fallback );
	}

	if ( is_page() ) {
		return kitstroy_get_post_field_value( 'seo_title', get_the_ID(), $fallback );
	}

	if ( is_post_type_archive( 'service' ) ) {
		return __( 'Услуги', 'kitstroy-moscow' );
	}

	if ( is_post_type_archive( 'portfolio' ) ) {
		return __( 'Портфолио', 'kitstroy-moscow' );
	}

	return '' !== $fallback ? $fallback : get_bloginfo( 'name', 'display' );
}

function kitstroy_get_meta_description(): string {
	if ( is_front_page() ) {
		return kitstroy_get_theme_option( 'home_seo_description', 'Проектирование, монтаж и пусконаладка систем электроснабжения, пожарной сигнализации, СКС, СКУД и видеонаблюдения в Москве и Московской области.' );
	}

	if ( is_singular( array( 'service', 'portfolio' ) ) ) {
		return kitstroy_get_post_field_value( 'seo_description', get_the_ID(), kitstroy_trim_words( get_the_excerpt() ?: get_the_content(), 28 ) );
	}

	if ( is_page() ) {
		return kitstroy_get_post_field_value( 'seo_description', get_the_ID(), kitstroy_trim_words( get_the_excerpt() ?: get_the_content(), 28 ) );
	}

	if ( is_singular( 'post' ) ) {
		return kitstroy_trim_words( get_the_excerpt() ?: get_the_content(), 28 );
	}

	if ( is_post_type_archive( 'service' ) ) {
		return __( 'Инженерные услуги по электромонтажу, пожарной сигнализации, СКС, СКУД, видеонаблюдению и сборке электрощитов.', 'kitstroy-moscow' );
	}

	if ( is_post_type_archive( 'portfolio' ) ) {
		return __( 'Примеры выполненных проектов по электроснабжению и слаботочным системам для квартир, домов, офисов и производственных объектов.', 'kitstroy-moscow' );
	}

	if ( is_home() ) {
		return __( 'Полезные статьи по электробезопасности, проектированию и эксплуатации инженерных систем.', 'kitstroy-moscow' );
	}

	return get_bloginfo( 'description' );
}

function kitstroy_get_og_image_url(): string {
	if ( is_singular() && has_post_thumbnail() ) {
		$image = wp_get_attachment_image_src( get_post_thumbnail_id(), 'large' );

		if ( $image ) {
			return $image[0];
		}
	}

	$organization = kitstroy_get_organization_data();
	$image        = kitstroy_get_image_data( $organization['og_image'], $organization['name'], 'large' );

	return $image['url'];
}

function kitstroy_get_canonical_url(): string {
	if ( is_404() ) {
		return '';
	}

	if ( is_search() ) {
		return get_search_link();
	}

	if ( is_paged() ) {
		return get_pagenum_link( kitstroy_get_archive_current_page() );
	}

	if ( is_singular() ) {
		return get_permalink();
	}

	if ( is_home() && get_option( 'page_for_posts' ) ) {
		return get_permalink( (int) get_option( 'page_for_posts' ) );
	}

	return kitstroy_get_current_url();
}

function kitstroy_filter_document_title_parts( array $title_parts ): array {
	if ( kitstroy_is_seo_plugin_active() ) {
		return $title_parts;
	}

	$title_parts['title'] = kitstroy_get_meta_title( isset( $title_parts['title'] ) ? (string) $title_parts['title'] : '' );

	return $title_parts;
}
add_filter( 'document_title_parts', 'kitstroy_filter_document_title_parts' );

function kitstroy_output_meta_tags(): void {
	if ( kitstroy_is_seo_plugin_active() ) {
		return;
	}

	$title       = kitstroy_get_meta_title( wp_get_document_title() );
	$description = kitstroy_get_meta_description();
	$canonical   = kitstroy_get_canonical_url();
	$og_image    = kitstroy_get_og_image_url();
	$og_url      = $canonical ?: home_url( '/' );
	$og_type     = is_singular( 'post' ) ? 'article' : 'website';

	if ( is_search() ) {
		echo "\n" . '<meta name="robots" content="noindex,follow">' . "\n";
	}

	if ( is_404() ) {
		echo "\n" . '<meta name="robots" content="noindex,noarchive">' . "\n";
	}

	echo "\n" . '<meta name="description" content="' . esc_attr( $description ) . '">' . "\n";

	if ( $canonical ) {
		echo '<link rel="canonical" href="' . esc_url( $canonical ) . '">' . "\n";
	}

	echo '<meta property="og:locale" content="ru_RU">' . "\n";
	echo '<meta property="og:type" content="' . esc_attr( $og_type ) . '">' . "\n";
	echo '<meta property="og:title" content="' . esc_attr( $title ) . '">' . "\n";
	echo '<meta property="og:description" content="' . esc_attr( $description ) . '">' . "\n";
	echo '<meta property="og:url" content="' . esc_url( $og_url ) . '">' . "\n";
	echo '<meta property="og:site_name" content="' . esc_attr( get_bloginfo( 'name' ) ) . '">' . "\n";
	echo '<meta property="og:image" content="' . esc_url( $og_image ) . '">' . "\n";
	echo '<meta name="twitter:card" content="summary_large_image">' . "\n";
	echo '<meta name="twitter:title" content="' . esc_attr( $title ) . '">' . "\n";
	echo '<meta name="twitter:description" content="' . esc_attr( $description ) . '">' . "\n";
	echo '<meta name="twitter:image" content="' . esc_url( $og_image ) . '">' . "\n";
}
add_action( 'wp_head', 'kitstroy_output_meta_tags', 2 );
