version: 2
updates:
  - package-ecosystem: npm
    directory: /portfolio-site
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'зависимости'
    groups:
      всё-сразу:
        patterns: ['*']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'действия'
